name: cosmic 43
on:
  schedule:
    - cron: "5 8 * * 3"
  workflow_dispatch:

jobs:
  build:
    name: Build cosmic
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate tags
        id: generate-tags
        shell: bash
        run: |
          TIMESTAMP="$(date +%Y%m%d)"
          BUILD_TAGS=("latest" "43")

          # Add timestamp tag for version history
          BUILD_TAGS+=("${TIMESTAMP}")

          echo "Generated the following tags: "
          for TAG in "${BUILD_TAGS[@]}"; do
              echo "${TAG}"
          done

          echo "alias_tags=${BUILD_TAGS[*]}" >> $GITHUB_OUTPUT
          echo "DEFAULT_TAG=latest" >> $GITHUB_ENV

      - name: Get current version
        id: labels
        uses: Wandalen/wretry.action@v3.5.0
        with:
          attempt_limit: 3
          attempt_delay: 15000
          command: |
            set -eo pipefail
            ver=$(skopeo inspect docker://ghcr.io/blue-build/base-images/fedora-cosmic:43 | jq -r '.Labels["org.opencontainers.image.version"]')
            if [ -z "$ver" ] || [ "null" = "$ver" ]; then
              echo "inspected image version must not be empty or null"
              exit 1
            fi
            echo "SOURCE_IMAGE_VERSION=$ver" >> $GITHUB_ENV

      - name: Image Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/zelf/cosmic
          labels: |
            org.opencontainers.image.title=cosmic
            org.opencontainers.image.version=${{ env.SOURCE_IMAGE_VERSION }}
            org.opencontainers.image.description=Custom COSMIC image.
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/zelf/bootc/main/README.md
            io.artifacthub.package.logo-url=https://avatars.githubusercontent.com/u/989504?v=4

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: ./desktop/cosmic/Containerfile
          image: ghcr.io/zelf/cosmic
          tags: ${{ steps.generate-tags.outputs.alias_tags }}
          labels: ${{ steps.meta.outputs.labels }}
          oci: true
          layers: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GHCR
        uses: Wandalen/wretry.action@v3.5.0
        id: push
        with:
          action: redhat-actions/push-to-registry@v2
          attempt_limit: 3
          attempt_delay: 15000
          with: |
            image: ghcr.io/zelf/cosmic
            tags: ${{ steps.build_image.outputs.tags }}
            registry: ghcr.io
            extra-args: |
              --disable-content-trust

      - uses: sigstore/cosign-installer@v3.7.0

      - name: Sign container image
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ steps.build_image.outputs.image }}@${TAGS}
        env:
          TAGS: ${{ steps.push.outputs.outputs && fromJSON(steps.push.outputs.outputs).digest }}
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}

      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
